# Generated by Django 2.1 on 2018-10-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('key', models.PositiveIntegerField(unique=True, verbose_name='Числовое значение')),
            ],
        ),
        migrations.AddField(
            model_name='moderatorrights',
            name='rights',
            field=models.ManyToManyField(to='moderation.SimpleRight', verbose_name='Права'),
        ),
        migrations.AddField(
            model_name='moderatorrights',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_rights', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
    ]
