# Generated by Django 2.1 on 2018-10-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст отзыва')),
                ('social_link', models.URLField(verbose_name='Ссылка на соц. сеть')),
                ('git_link', models.URLField(verbose_name='Ссылка на гит')),
                ('moderated', models.BooleanField(default=False, verbose_name='Модерировано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
