# Generated by Django 2.1 on 2018-10-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import backend.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(editable=False, null=True)),
                ('width', models.IntegerField(editable=False, null=True)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to=backend.utils.models.create_path, verbose_name='Изображение', width_field='width')),
                ('username', models.CharField(editable=False, max_length=50)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('is_forum_moderator', models.BooleanField(default=False, verbose_name='Модератор')),
                ('completed_courses', models.ManyToManyField(blank=True, to='courses.Course', verbose_name='Пройденные курсы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователь',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
